meta_product_name: "Mango"
meta_title: "Mango - Never eat alone!"
meta_description: "Never eat alone! Problem solved always have a companion to eat with when out."
meta_image: "homepage.jpg" # should exist in `app/assets/images/`
